/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ml_CONSTANTS_H
#define ml_CONSTANTS_H

#include "ml_types.h"



class mlConstants {
 public:
  mlConstants();

};

extern const mlConstants g_ml_constants;



#endif
