// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MLEngine.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class MLEngineHandler : virtual public MLEngineIf {
 public:
  MLEngineHandler() {
    // Your initialization goes here
  }

  double Predict(const int32_t id, const std::string& x) {
    // Your implementation goes here
    printf("Predict\n");
  }

  void Learn(const std::string& x, const double y) {
    // Your implementation goes here
    printf("Learn\n");
  }

  void LearnFromID(const int32_t id) {
    // Your implementation goes here
    printf("LearnFromID\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MLEngineHandler> handler(new MLEngineHandler());
  shared_ptr<TProcessor> processor(new MLEngineProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

